### ISSUE TITLE
Regex does not factor in symbols in front of/behind trigger words

### ISSUE THREAD

**Issue by OlFarmerMcNinja** [OlFarmerMcNinja/Mr-Manager-Bot#2]

**Comment by engineerchange** [comment]
Sounds like a feature, not a bug. 😛

**Comment by OlFarmerMcNinja** [comment]
Bug fixed by removing the poor attempt at natural language processing via regex. Now the bot responds to  "LED <on/off>" Will attempt to implement a NLP solution way down the line though. I really like the idea of it.
